---
development:
  DB_FILENAME: db/dev.db
  DB_KEY: 'uo+NjFvxXgFjoScigLKl132LWO0R6/nHvglkzxkjA10='
  SECURE_SCHEME: HTTP
  
test:
  DB_FILENAME: db/test.db
  SECURE_SCHEME: HTTP

production:
  SECURE_SCHEME: HTTPS