---
development:
  DB_FILENAME: db/dev.db
  SECURE_SCHEME: HTTP
  API_URL: http://localhost:9292/api/v1
  APP_URL: http://localhost:3000

  
test:
  DB_FILENAME: db/test.db
  SECURE_SCHEME: HTTP
  API_URL: http://localhost:9292/api/v1
  APP_URL: http://localhost:3000


production:
  SECURE_SCHEME: HTTPS
