---
development:
  DB_KEY: 'uo+NjFvxXgFjoScigLKl132LWO0R6/nHvglkzxkjA10='
  MSG_KEY: '5VZCYir/+RpoIv+soOcz0gZEWcnM910Mv6Z6SDTDRXg='
  SENDGRID_KEY: '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'

test:
  DB_KEY: 'uo+NjFvxXgFjoScigLKl132LWO0R6/nHvglkzxkjA10='
  MSG_KEY: '5VZCYir/+RpoIv+soOcz0gZEWcnM910Mv6Z6SDTDRXg='
  SENDGRID_KEY: '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'

production:
  DB_KEY: 'uo+NjFvxXgFjoScigLKl132LWO0R6/nHvglkzxkjA10='
  MSG_KEY: '5VZCYir/+RpoIv+soOcz0gZEWcnM910Mv6Z6SDTDRXg='
  SENDGRID_KEY: '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'

