---
development:
  DB_KEY: 'uo+NjFvxXgFjoScigLKl132LWO0R6/nHvglkzxkjA10='
  MSG_KEY: '5VZCYir/+RpoIv+soOcz0gZEWcnM910Mv6Z6SDTDRXg='
  SENDGRID_KEY: "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"
  SIGNING_KEY: "EL9j1WuNH9LdmKc2omVcou02Tkyldt/25wRi6LLcODA="
  VERIFY_KEY: bqQc6L8x5vXBa7c/iGjtVD9tdr6KDfkpmB8zVFSwcCM=

test:
  DB_KEY: 'uo+NjFvxXgFjoScigLKl132LWO0R6/nHvglkzxkjA10='
  MSG_KEY: '5VZCYir/+RpoIv+soOcz0gZEWcnM910Mv6Z6SDTDRXg='
  SENDGRID_KEY: "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"

production:
  DB_KEY: 'uo+NjFvxXgFjoScigLKl132LWO0R6/nHvglkzxkjA10='
  MSG_KEY: '5VZCYir/+RpoIv+soOcz0gZEWcnM910Mv6Z6SDTDRXg='
  SENDGRID_KEY: "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"