---
development:
  DB_KEY: 'uo+NjFvxXgFjoScigLKl132LWO0R6/nHvglkzxkjA10='
  MSG_KEY: '5VZCYir/+RpoIv+soOcz0gZEWcnM910Mv6Z6SDTDRXg='
  SENDGRID_KEY: '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'
  SIGNING_KEY: EL9j1WuNH9LdmKc2omVcou02Tkyldt/25wRi6LLcODA=
  VERIFY_KEY: bqQc6L8x5vXBa7c/iGjtVD9tdr6KDfkpmB8zVFSwcCM=

test:
  DB_KEY: 'uo+NjFvxXgFjoScigLKl132LWO0R6/nHvglkzxkjA10='
  MSG_KEY: '5VZCYir/+RpoIv+soOcz0gZEWcnM910Mv6Z6SDTDRXg='
  SENDGRID_KEY: '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'

production:
  DB_KEY: 'uo+NjFvxXgFjoScigLKl132LWO0R6/nHvglkzxkjA10='
  MSG_KEY: '5VZCYir/+RpoIv+soOcz0gZEWcnM910Mv6Z6SDTDRXg='
  SENDGRID_KEY: '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'