---
development:
  DB_KEY: 'uo+NjFvxXgFjoScigLKl132LWO0R6/nHvglkzxkjA10='
  MSG_KEY: <replace with crypto key `rake generate:msg_key`>
  SENDGRID_KEY: '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'

test:
  DB_KEY: 'uo+NjFvxXgFjoScigLKl132LWO0R6/nHvglkzxkjA10='
  MSG_KEY: <replace with crypto key `rake generate:msg_key`>
  SENDGRID_KEY: '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'

production:
  DB_KEY: 'uo+NjFvxXgFjoScigLKl132LWO0R6/nHvglkzxkjA10='
  MSG_KEY: <replace with crypto key `rake generate:msg_key`>
  SENDGRID_KEY: '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'



require 'sendgrid-ruby'
include SendGrid

from = Email.new(email: 'phiwokuhlegondwe@gmail.com')
to = Email.new(email: 'gondwephiwokuhle@gmail.com')
subject = 'Sending with SendGrid is Fun'
content = Content.new(type: 'text/plain', value: 'and easy to do anywhere, even with Ruby')
mail = Mail.new(from, subject, to, content)

sg = SendGrid::API.new(api_key: ENV['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'])
response = sg.client.mail._('send').post(request_body: mail.to_json)
puts response.status_code
puts response.body
puts response.headers